[0m09:55:45.920330 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105167650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105177ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105177e90>]}


============================== 09:55:45.922107 | d2b34ffc-e5fd-4b87-ba20-f05512db40ec ==============================
[0m09:55:45.922107 [info ] [MainThread]: Running with dbt=1.5.4
[0m09:55:45.922413 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/andremoleiro/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:55:45.922791 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andremoleiro/Documents/Learning/learning-repo/dbt/dbt_exam_preparation/dbt_projects/refactoring_for_modularity/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:55:45.923182 [debug] [MainThread]: Command `dbt docs generate` failed at 09:55:45.923123 after 0.01 seconds
[0m09:55:45.923367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105180690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105161f50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105174210>]}
[0m09:55:45.923540 [debug] [MainThread]: Flushing usage events
[0m09:56:02.522485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10646e850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1064675d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106467e10>]}


============================== 09:56:02.524262 | 1ce2aa7f-ba2f-4b4a-a439-d49cd05e7720 ==============================
[0m09:56:02.524262 [info ] [MainThread]: Running with dbt=1.5.4
[0m09:56:02.524582 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/andremoleiro/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:56:02.524868 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/andremoleiro/Documents/Learning/learning-repo/dbt/dbt_exam_preparation/dbt_projects/refactoring_for_modularity/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:56:02.525254 [debug] [MainThread]: Command `dbt docs serve` failed at 09:56:02.525195 after 0.01 seconds
[0m09:56:02.525433 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10647fdd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10645e150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10645e8d0>]}
[0m09:56:02.525618 [debug] [MainThread]: Flushing usage events
